name: CI

on:
  push:
    branches:
      - develop
      - master
      - 'release/**'

  pull_request:
    branches:
      - develop
      - master
      - 'release/**'

env:
  TEST_WITH_NETWORK: 1

jobs:
  run-tests:
    strategy:
      fail-fast: false 
      matrix:
        perl:
          - '5.40'
          - '5.36'
          - '5.26'
        runner:
          - ubuntu-22.04

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: perl version
        run: perl -v

      - name: apt install
        run: sudo apt install -y libidn2-dev

      - name: cpan module
        run: cpanm Devel::CheckLib ExtUtils::PkgConfig Module::Install Module::Install::XSUtil Test::Exception Test::Fatal 

      - name: installation
        run: cpanm --verbose --notest --configure-args="--no-ed25519" .

      - name: test
        run: prove -bl

  build-artifact:
    needs: run-tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: apt install
        run: sudo apt-get install -y git build-essential libmodule-install-perl libdevel-checklib-perl libextutils-pkgconfig-perl libmodule-install-xsutil-perl libssl-dev libidn2-dev

      - name: build
        run: perl Makefile.PL && make all dist

      - name: Get short SHA
        id: short_sha
        run: |
            if [ "${{ github.event_name }}" == "pull_request" ]; then
                echo "SHORT_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV
            else
                echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
            fi

      - name: Get Zonemaster-LDNS version 
        id: version
        run: |
          result=`grep 'our $VERSION' lib/Zonemaster/LDNS.pm`
          result+='printf $VERSION;'
          VERSION=`perl -e "$result"`
          echo "version=$VERSION" >> $GITHUB_OUTPUT
     
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zonemaster-LDNS-${{ steps.version.outputs.version }}-${{ env.SHORT_SHA }}
          path: Zonemaster-LDNS-${{ steps.version.outputs.version }}.tar.gz
